on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: "build"
          working-directory: "llvm"
          run: "./build.sh"

        - name: "test"
          working-directory: "llvm"
          run: "./build_benchmark.sh"
